### ISSUE TITLE
pi zero w - cannot find module

### ISSUE THREAD

**Issue by mentaluproar** [oandrew/ipod-gadget#12]
I cannot figure out where to put the modules so modules.conf can get systemd to load them automatically at startup.

**Comment by oandrew** [comment]
You need to install them using make.
If you build on the same machine where you use them then you can simply run this from the same directory where you built the modules:
```
$ make -C /lib/modules/$(uname -r)/build M=$PWD modules_install
$ modinfo g_ipod_gadget # should find it 
```

More info here:
https://www.kernel.org/doc/Documentation/kbuild/modules.txt

Also check out DKMS:
https://github.com/oandrew/ipod-gadget/pull/8
https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support
