### ISSUE TITLE
combine with bluetooth

### ISSUE THREAD

**Issue by VincentGijsen** [oandrew/ipod-gadget#16]
Hi Andrew,

nice stuff, and unfortunate that my Go knowledge is rather limited (you wouldn't happen to have a C(++) port lying arround ;). Was thinking to combine your code with bluetooth, e.g. a module that support AVRCP1.5, and i2S and use AVRCP to replicate playlists/audiobooks/..., ctrl over uart and audio through I2S input (e.g. with the IS2020 family modules of microchip), or venture into the use of the bluetooth module on the pi zero and use AVRCP from there, however than just with SBC coded. Or i could try to port all to a custom-android-rom..

This way i'm hoping to build a bluetooth-dock experience for my car, regardless of android/ios and (in my case) the required physical connection by usb.

I haven't checked-out your code that thorough, but i guess the IAP protocol supports these features as well, and would be possible with your code-base?

**Comment by oandrew** [comment]
Check this out: https://github.com/geniass/pipod
