### ISSUE TITLE
0x64 "RequestApplicationLaunch" error

### ISSUE THREAD

**Issue by arturopolanco** [oandrew/ipod-gadget#18]
Hi all,

I'm unable to play anything, the speaker test fails with a _Write error: -5,Input/output error, xrun_recovery failed: -5,Input/output error__

I'm using some old Libratone speakers and it's the same for both. I only see an error for the command _0x64 "RequestApplicationLaunch"_ but is that causing the issue? It's just an application launch and it only appears once.  

[ipod.trace.txt](https://github.com/oandrew/ipod-gadget/files/5113964/ipod.trace.txt)

I would really appreciate some hints here :)
Thanks a lot!

**Comment by oandrew** [comment]
hi @arturopolanco 
I just pushed a change to handle this message. 
It's possible the speaker was waiting for a response.

It's also possible it starts streaming only when `dispremote.RetPlayStatus` returns Playing status:
https://github.com/oandrew/ipod/blob/master/lingo-dispremote/handler.go#L110

**Comment by arturopolanco** [comment]
Hey @oandrew ,

Thanks a lot.  The 0x64 answer didn't do the trick but I don't see any errors.  Then I set the Playing status to 1 and was able to successfully run the speaker-test.    Now I'll continue with a snapcast to stream audio to it.  

Thanks a lot, once again.  🥇

**Comment by oandrew** [comment]
@arturopolanco 
glad it worked!
also, could you share a trace of a successful communication?

**Comment by arturopolanco** [comment]
Hi @oandrew 

Here it is. 
[ipod.trace.txt](https://github.com/oandrew/ipod-gadget/files/5128323/ipod.trace.txt)

Thanks for the support :)
