### ISSUE TITLE
All looks good, but can't stream sound

### ISSUE THREAD

**Issue by LazyCloner** [oandrew/ipod-gadget#19]
Hello there, 

I was able to install everything well, the client launch correctly, I can connect it to my car and I have `Attached iPod Device` on my car screen. But when I tried to run a sound test I have :
>pi@raspberrypi:~ $ speaker-test -D plughw:CARD=iPodUSB,DEV=0 -c 2 -r 44100
>...
>Playback device is plughw:CARD=iPodUSB,DEV=0
>...
>Write error: -5,Input/output error
>xrun_recovery failed: -5,Input/output error
>Transfer failed: Input/output error

I'm working on a raspi zero W (raspian 5.4.51).
And the sound card show up with aplay -l .
The trace file only have the 2 following lines :
>< 08 00 55 0E 00 13 00 00 04 11 00 00 00 02 00 00 02 00 C6 00 00
>\> 01 00 55 04 00 02 00 13 E7 00 00 00 00

And thank you for your code oandrew !

**Comment by oandrew** [comment]
Hi, @LazyCloner 

Current master might fix the issue for you.
Audio should be working once you see `type=audio.TrackNewAudioAttributes` message in the log

**Comment by LazyCloner** [comment]
Hi, thank you for your help !

It seem like it works better now but after `type=audio.TrackNewAudioAttributes` the audio device is still closed.

`pi@raspi:~ $ sudo speaker-test -D plughw:CARD=iPodUSB,DEV....`
`...`
`Write error: -5, Input/output error`
`pi@raspi:~ $ cat /proc/asound/iPodUSB/pcm0p/sub0/status`
`closed`

But the communication doesn't stuck anymore after `GetDevAuthentificationInfo`.

I'll upload the trace in 1h. (And I'll try to set the PlayingStatus to 1)

PS : I tried with kernel 4.19 and golang versions 1.13 and 1.15

**Comment by oandrew** [comment]
@LazyCloner Try current master when you have a chance

**Comment by LazyCloner** [comment]
Hi @oandrew ! 
Thank you for your time.
But unfortunately nothing changed. The audio device is still closed and the trace file is exactly same as the previous one.

Have a good day !

**Comment by oandrew** [comment]
@LazyCloner hmm.. 
trace file can't be the same because I fixed a bug in the most recent commit. 

https://github.com/oandrew/ipod/commit/05257f6644a7bdc025d71284705df31489d6ac8d

**Comment by LazyCloner** [comment]
Ok, I'll double check if I clone it well

**Comment by LazyCloner** [comment]
So with the current master, I can now open the sound device but I could only ear like a white noise sound. And the program seem to be in a loop. There is the trace file. 
In second, on my car screen, it's writen "PAUSED"
Is the trace file look like normal ?

PS : I will add the trace file tommorow.

**Comment by oandrew** [comment]
@LazyCloner This is great! White noise is what you are supposed to hear - https://linux.die.net/man/1/speaker-test. It means everything is working.

**Comment by LazyCloner** [comment]
Oh nice ! Thank you so much Andrew !
I will to do 2 more try before closing the issue.
Thanks for your time, Is there a place to give some little donation ?

**Comment by pavelkrotkov** [comment]
Similar problem here - install went well, but no sound coming out in the speaker test.
Compiled using go 1.15 on the latest RPi OS with kernel 5.4.72+.
ipod trace prints this error message inline, full file attached.

ERRO[0411.607895] << CMD                                        error=ipod.Command unmarshal: unknown cmd 0x00,0x0d id=0x00,0x0d trx=<nil> type=ipod.UnknownPayload

[ipod.trace.txt](https://github.com/oandrew/ipod-gadget/files/5505569/ipod.trace.txt)
