### ISSUE TITLE
Denon RCD-M38 not working

### ISSUE THREAD

**Issue by oandrew** [oandrew/ipod-gadget#21]
Similar problem here - install went well, but no sound coming out in the speaker test.
Compiled using go 1.15 on the latest RPi OS with kernel 5.4.72+.
ipod trace prints this error message inline, full file attached.

ERRO[0411.607895] << CMD                                        error=ipod.Command unmarshal: unknown cmd 0x00,0x0d id=0x00,0x0d trx=<nil> type=ipod.UnknownPayload

[ipod.trace.txt](https://github.com/oandrew/ipod-gadget/files/5505569/ipod.trace.txt)

_Originally posted by @pavelkrotkov in https://github.com/oandrew/ipod-gadget/issues/19#issuecomment-723503539_

**Comment by oandrew** [comment]
@pavelkrotkov Moving your comment to a separate issue.

Try current master - https://github.com/oandrew/ipod/commit/48eb8573ea7f587a91da41b88aa26950f65e86f0 might fix your issue

**Comment by pavelkrotkov** [comment]
It worked! I can stream to it via airplay now.

**Comment by pavelkrotkov** [comment]
Thank you, Andrew

**Comment by oandrew** [comment]
Awesome! Could you share a trace file when you have a chance? Thanks

**Comment by pavelkrotkov** [comment]
PFA [ipod.trace.txt](https://github.com/oandrew/ipod-gadget/files/5514583/ipod.trace.txt)
