### ISSUE TITLE
Unable to load driver in Raspberry Pi W

### ISSUE THREAD

**Issue by akuholla** [oandrew/ipod-gadget#6]
Hello! I am trying to compile this project on a Raspberry Pi W. I did read the other issues submitted here and I was able to compile the module (.ko) successfully but cannot load the driver successfully. I do not see the `/dev/iap0` file

I do not get any error messages while insmod. Here is the output of my dmesg:

[  947.290461] g_ipod_audio: loading out-of-tree module taints kernel.

[  947.291711] **********************************************************
[  947.291715] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[  947.291720] **                                                      **
[  947.291725] ** trace_printk() being used. Allocating extra memory.  **
[  947.291729] **                                                      **
[  947.291733] ** This means that this is a DEBUG kernel and it is     **
[  947.291737] ** unsafe for production use.                           **
[  947.291741] **                                                      **
[  947.291745] ** If you see this message and you are not debugging    **
[  947.291750] ** the kernel, report this immediately to your vendor!  **
[  947.291754] **                                                      **
[  947.291757] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[  947.291761] **********************************************************
[  968.196558] ipod-gadget: init
**[  968.196581] udc-core: couldn't find an available UDC - added [g_ipod] to list of pending drivers**

Output of my lsmod:

Module                  Size  Used by
g_ipod_gadget           5064  0
g_ipod_hid             10037  0
g_ipod_audio            9098  0
libcomposite           48212  3 g_ipod_gadget,g_ipod_hid,g_ipod_audio
udc_core               38862  3 g_ipod_hid,libcomposite,g_ipod_audio
cmac                    3230  1
bnep                   11981  2
hci_uart               26546  1
btbcm                   8248  1 hci_uart
serdev                  9370  1 hci_uart
bluetooth             366847  24 hci_uart,bnep,btbcm
ecdh_generic           17649  1 bluetooth
brcmfmac              273198  0
brcmutil                9114  1 brcmfmac
snd_bcm2835            22991  0
snd_pcm                89590  2 snd_bcm2835,g_ipod_audio
cfg80211              542242  1 brcmfmac
snd_timer              22396  1 snd_pcm
rfkill                 21476  6 bluetooth,cfg80211
snd                    60154  4 snd_timer,snd_bcm2835,g_ipod_audio,snd_pcm
uio_pdrv_genirq         3718  0
uio                     9901  1 uio_pdrv_genirq
fixed                   3033  0
ip_tables              12427  0
x_tables               22098  1 ip_tables
ipv6                  401778  22

Please Help _/\_

**Comment by oandrew** [comment]
Hi!
Most likely the usb controller driver is not in dual-role mode (when it can be a host or a device).

this tutorial might help:
https://learn.adafruit.com/turning-your-raspberry-pi-zero-into-a-usb-gadget/overview
