### ISSUE TITLE
Suzuki Swift cant connect

### ISSUE THREAD

**Issue by MR-R080T** [oandrew/ipod-gadget#7]
Hello i am trying to use a RPI Zero W with a suzuki swift 2012 radio. i can start the ipod driver but cant play any audio to the car as speeker test produces an error of 

```
Write error: -5,Input/output error
xrun_recovery failed: -5,Input/output error
Transfer failed: Input/output error

```
and the car eventually flashes error 1

the trace is below 

```
< 0E 00 55 04 00 38 00 01 C3 00
> 03 00 55 06 00 02 00 01 00 38 BF 00 00 00
< 11 00 55 15 00 39 00 02 01 0F 00 00 04 00 03 04 0A 00 00 00 02 00 00 02 00 87
> 03 00 55 09 00 3A 00 02 01 03 00 00 00 B7
< 11 00 55 10 00 39 00 03 01 0A 00 01 00 00 00 00 00 00 00 10 98 00 00 00 00 00
> 03 00 55 09 00 3A 00 03 01 03 00 01 00 B5
< 12 00 55 1C 00 39 00 04 01 16 00 02 01 43 61 72 41 63 63 65 73 73 6F 72 79 53 79 73 74 65 6D 00 46 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 04 00 55 0A 00 3A 00 04 01 04 00 02 00 01 B0 00 00 00
< 10 00 55 0C 00 39 00 05 01 06 00 02 04 01 00 00 A8 00
> 04 00 55 0A 00 3A 00 05 01 04 00 02 00 04 AC 00 00 00
< 10 00 55 0C 00 39 00 06 01 06 00 02 05 01 00 00 A6 00
> 04 00 55 0A 00 3A 00 06 01 04 00 02 00 05 AA 00 00 00
< 12 00 55 22 00 39 00 07 01 1C 00 02 06 53 55 5A 55 4B 49 20 4D 4F 54 4F 52 20 43 4F 52 50 4F 52 41 54 49 4F 4E 00 6D 00 00 00 00 00 00 00 00 00 00 00
> 04 00 55 0A 00 3A 00 07 01 04 00 02 00 06 A8 00 00 00
< 12 00 55 16 00 39 00 08 01 10 00 02 07 69 50 6F 64 20 43 6F 6E 74 72 6F 6C 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 04 00 55 0A 00 3A 00 08 01 04 00 02 00 07 A6 00 00 00
< 10 00 55 0D 00 39 00 09 01 07 00 02 0C 00 00 00 00 9B
> 04 00 55 0A 00 3A 00 09 01 04 00 02 00 0C A0 00 00 00
< 0E 00 55 05 00 3B 00 0A 00 B6
> 02 00 55 05 00 3C 00 0A 00 B5
> 02 00 55 04 00 14 00 01 E7 00
< 10 00 55 00 00 08 00 15 00 01 02 00 02 01 DD 00 00 00
```
i have built a small python program to use this as a bluetooth adapter for my girlfriends car radio and hope to give it to her for Christmas any help would be greatly appreciated

**Comment by oandrew** [comment]
Hi!
For some reason the radio is not sending the certificate information.
I've pushed a branch with a change to ignore that.
https://github.com/oandrew/ipod/tree/accept-empty-cert

The audio will be available only if the authentication process completes successfully.

**Comment by MR-R080T** [comment]
I am building it now and will report back thanks for your help

**Comment by MR-R080T** [comment]
Exact same issue with tracelog below

`< 0E 00 55 04 00 38 00 01 C3 00
> 03 00 55 06 00 02 00 01 00 38 BF 00 00 00
< 11 00 55 15 00 39 00 02 01 0F 00 00 04 00 03 04 0A 00 00 00 02 00 00 02 00 87
> 03 00 55 09 00 3A 00 02 01 03 00 00 00 B7
< 11 00 55 10 00 39 00 03 01 0A 00 01 00 00 00 00 00 00 00 10 98 00 00 00 00 00
> 03 00 55 09 00 3A 00 03 01 03 00 01 00 B5
< 12 00 55 1C 00 39 00 04 01 16 00 02 01 43 61 72 41 63 63 65 73 73 6F 72 79 53 79 73 74 65 6D 00 46 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 04 00 55 0A 00 3A 00 04 01 04 00 02 00 01 B0 00 00 00
< 10 00 55 0C 00 39 00 05 01 06 00 02 04 01 00 00 A8 00
> 04 00 55 0A 00 3A 00 05 01 04 00 02 00 04 AC 00 00 00
< 10 00 55 0C 00 39 00 06 01 06 00 02 05 01 00 00 A6 00
> 04 00 55 0A 00 3A 00 06 01 04 00 02 00 05 AA 00 00 00
< 12 00 55 22 00 39 00 07 01 1C 00 02 06 53 55 5A 55 4B 49 20 4D 4F 54 4F 52 20 43 4F 52 50 4F 52 41 54 49 4F 4E 00 6D 00 00 00 00 00 00 00 00 00 00 00
> 04 00 55 0A 00 3A 00 07 01 04 00 02 00 06 A8 00 00 00
< 12 00 55 16 00 39 00 08 01 10 00 02 07 69 50 6F 64 20 43 6F 6E 74 72 6F 6C 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 04 00 55 0A 00 3A 00 08 01 04 00 02 00 07 A6 00 00 00
< 10 00 55 0D 00 39 00 09 01 07 00 02 0C 00 00 00 00 9B
> 04 00 55 0A 00 3A 00 09 01 04 00 02 00 0C A0 00 00 00
< 0E 00 55 05 00 3B 00 0A 00 B6
> 02 00 55 05 00 3C 00 0A 00 B5
> 02 00 55 04 00 14 00 01 E7 00
< 10 00 55 00 00 08 00 15 00 01 02 00 02 01 DD 00 00 00
< 10 00 55 00 00 08 00 15 00 01 02 00 03 01 DC 00 00 00`

but now throwing up this error
ERRO[0092.324627] << CMD error=ipod.Command unmarshal: BinaryUnmarshaler: short packet id=0x00,0x15 trx=0x0001 type=<nil>
